CREATE TABLE IF NOT EXISTS lieux (
  id SERIAL PRIMARY KEY,
  nom TEXT     NOT NULL,
  type TEXT    NOT NULL,
  adresse TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL
);
