version: '3.8'

services:
  db:
    image: postgres:15
    container_name: spothelp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0604
      POSTGRES_DB: spothelp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
